# Generated by Django 5.0.2 on 2024-02-26 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_staff_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_leave',
            old_name='data',
            new_name='date',
        ),
    ]
