# Generated by Django 5.0.2 on 2024-02-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0015_attendance_attendance_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
    ]
