# Generated by Django 5.0.2 on 2024-02-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0017_studentresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
